from django.shortcuts import render
from .aluno import AlunoViewSet
from .avaliacao import AvaliacaoViewSet
from .bolsa_pesquisa import Bolsa_PesquisaViewSet
from .curso import CursoViewSet
from .disciplina import DisciplinaViewSet
from .frequencia import FrequenciaViewSet
from .matricula import MatriculaViewSet
from .professor import ProfessorViewSet
from .projeto_extracurricular import Projeto_ExtracurricularViewSet
from .turma import TurmaViewSet