# Generated by Django 5.2.3 on 2025-06-19 23:57

import django.core.validators
import django.db.models.deletion
import localflavor.br.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=45)),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=45)),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('formacao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('carga_horaria', models.IntegerField()),
                ('ementa', models.CharField(max_length=500)),
                ('avaliacoes', models.ManyToManyField(related_name='avaliacoes', to='escola.avaliacao')),
                ('professores', models.ManyToManyField(related_name='professores', to='escola.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('carga_horaria', models.IntegerField()),
                ('descricao', models.CharField(max_length=500)),
                ('disciplinas', models.ManyToManyField(related_name='disciplinas', to='escola.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('num_matricula', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('A', 'Ativa'), ('I', 'Inativa'), ('P', 'Pendente')], default='P', max_length=1)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='aluno', to='escola.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='escola.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data_aula', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('J', 'Justificado')], default='A', max_length=1)),
                ('obvervacoes', models.CharField(max_length=255)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='escola.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto_Extracurricular',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('ementa', models.CharField(max_length=500)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('professor_orientador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projeto_extracurricular', to='escola.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Bolsa_Pesquisa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('projeto_extracurricular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bolsa_pesquisa', to='escola.projeto_extracurricular')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('num_turma', models.IntegerField()),
                ('num_alunos', models.IntegerField()),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='escola.curso')),
                ('matriculas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='escola.matricula')),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='turmas',
            field=models.ManyToManyField(related_name='turmas', to='escola.turma'),
        ),
    ]
