# Generated by Django 5.2.3 on 2025-06-12 12:25

import localflavor.br.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=45)),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('num_matricula', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('A', 'Ativa'), ('I', 'Inativa'), ('P', 'Pendente')], default='P', max_length=1)),
            ],
        ),
    ]
