# Generated by Django 5.2.3 on 2025-06-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto_extracurricular',
            options={'verbose_name_plural': 'Projetos_Extracurriculares'},
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='turmas',
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='avaliacoes',
            field=models.ManyToManyField(blank=True, related_name='avaliacoes', to='escola.avaliacao'),
        ),
    ]
