# Generated by Django 5.2.3 on 2025-06-20 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_projeto_extracurricular_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='matriculas',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='num_alunos',
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='escola.turma'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='obvervacoes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
