# Generated by Django 5.2.3 on 2025-06-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_remove_turma_matriculas_remove_turma_num_alunos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='tipo',
            new_name='tema',
        ),
        migrations.AlterField(
            model_name='turma',
            name='num_turma',
            field=models.IntegerField(blank=True),
        ),
    ]
