# Generated by Django 5.2.3 on 2025-06-20 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_rename_tipo_avaliacao_tema_alter_turma_num_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='avaliacoes',
        ),
    ]
