# Generated by Django 5.2.3 on 2025-06-20 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_avaliacao_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='disciplina',
        ),
    ]
