# Generated by Django 5.2.3 on 2025-06-20 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_remove_avaliacao_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='escola.disciplina'),
        ),
    ]
