# Generated by Django 5.2.3 on 2025-06-20 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0008_avaliacao_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='data',
            field=models.DateField(default=datetime.date(2025, 6, 20)),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='professores',
            field=models.ManyToManyField(related_name='disciplinas', to='escola.professor'),
        ),
    ]
