# Generated by Django 5.2.3 on 2025-06-20 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0009_alter_avaliacao_data_alter_disciplina_professores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='escola.turma'),
        ),
    ]
