# Generated by Django 5.2.3 on 2025-06-20 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0010_alter_frequencia_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='obvervacoes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='escola.matricula'),
        ),
    ]
