# Generated by Django 5.2.3 on 2025-06-20 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0011_alter_frequencia_obvervacoes_alter_frequencia_turma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequencia',
            old_name='turma',
            new_name='matricula',
        ),
        migrations.AlterField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='escola.aluno'),
        ),
    ]
