# Generated by Django 5.2.3 on 2025-06-26 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0012_rename_turma_frequencia_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='data',
            field=models.DateField(default=datetime.date(2025, 6, 26)),
        ),
    ]
