# Generated by Django 5.2.3 on 2025-06-26 12:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0012_rename_turma_frequencia_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='data',
            field=models.DateField(default=datetime.date(2025, 6, 26)),
        ),
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
