from .aluno import AlunoSerializer
from .matricula import MatriculaSerializer
from .turma import TurmaSerializer
from .curso import CursoSerializer
from .disciplina import DisciplinaSerializer
from .avaliacao import AvaliacaoSerializer
from .professor import ProfessorSerializer
from .frequencia import FrequenciaSerializer
from .projeto_extracurricular import Projeto_ExtracurricularSerializer
from .bolsa_pesquisa import Bolsa_PesquisaSerializer
