from .aluno import Aluno
from .matricula import Matricula
from .turma import Turma
from .curso import Curso
from .disciplina import Disciplina
from .avaliacao import Avaliacao
from .professor import Professor
from .frequencia import Frequencia
from .projeto_extracurricular import Projeto_Extracurricular
from .bolsa_pesquisa import Bolsa_Pesquisa
